---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/rsync -av --exclude='.git' --exclude='.cpanel.yml' --exclude='_deploy-backup' --exclude='node_modules' --exclude='.github' ./ $DEPLOYPATH
